# Generated by Django 3.0 on 2019-12-02 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.CharField(max_length=10, verbose_name='Numer meczu')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data i godzina')),
            ],
            options={
                'verbose_name': 'Mecz',
                'verbose_name_plural': 'Mecze',
                'ordering': ('date_time',),
            },
        ),
        migrations.CreateModel(
            name='MatchCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kateogria meczu')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='MatchStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('next_status', models.IntegerField(blank=True, null=True, verbose_name='Nastepny status')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa drużyny')),
                ('city', models.CharField(max_length=50, verbose_name='Miasto')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Numer kontaktowy')),
            ],
            options={
                'verbose_name': 'Drużyna',
                'verbose_name_plural': 'Druzyny',
            },
        ),
        migrations.CreateModel(
            name='RefereeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_level', models.IntegerField(choices=[(1, 'Zwiazkowy'), (2, 'Okregowy')], default=1, verbose_name='Poziom sędziego')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Miasto')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Numer telefonu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ref_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sędzia szczegóły',
                'verbose_name_plural': 'Sedziowie szcezgóły',
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_goals', models.IntegerField(blank=True, null=True, verbose_name='Bramki Gospodarze')),
                ('away_team_goals', models.IntegerField(blank=True, null=True, verbose_name='Bramki Goscie')),
                ('winner', models.CharField(blank=True, max_length=1, null=True, verbose_name='Zwyciezca')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referee.Match', verbose_name='Mecz')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_team', to='referee.Team', verbose_name='Gosc'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_team', to='referee.Team', verbose_name='Gospodarz'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='referee.MatchCategory', verbose_name='Kategoria'),
        ),
        migrations.AddField(
            model_name='match',
            name='referee_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_a', to=settings.AUTH_USER_MODEL, verbose_name='Sędzia A'),
        ),
        migrations.AddField(
            model_name='match',
            name='referee_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_b', to=settings.AUTH_USER_MODEL, verbose_name='Sędzia B'),
        ),
    ]
