# Generated by Django 3.0 on 2020-01-03 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refereedetails',
            options={'verbose_name': 'Sędzia szczegóły', 'verbose_name_plural': 'Sedziowie szczegóły'},
        ),
        migrations.AddField(
            model_name='match',
            name='match_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referee.MatchStatus', verbose_name='Status meczu'),
        ),
    ]
