# Generated by Django 3.0 on 2020-01-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0003_auto_20200103_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('id',), 'verbose_name': 'Drużyna', 'verbose_name_plural': 'Druzyny'},
        ),
    ]
